const ADD_PLAYER = "ADD_PLAYER";
const UPDATE_PLAYER = "UPDATE_PLAYER";
const DELETE_PLAYER = "DELETE_PLAYER";
const ADD_ITEMS = "ADD_ITEMS";
const DELETE_ITEMS = "DELETE_ITEMS";
const UPDATE_ITEMS = "UPDATE_ITEMS";